"""
config.py — Central configuration for IWMRO.

All tuneable parameters live here so every module imports from one
place, making the system easy to adapt for production deployments
(e.g. scaling from 50 to 1 000+ bins requires only this file).
"""

from pathlib import Path

# ── Project root ────────────────────────────────────────────────────────────
ROOT_DIR = Path(__file__).parent

# ── Directory layout ─────────────────────────────────────────────────────────
DIRS = {
    "models":    ROOT_DIR / "models",
    "raw":       ROOT_DIR / "data" / "raw",
    "processed": ROOT_DIR / "data" / "processed",
    "exports":   ROOT_DIR / "data" / "exports",
}

# Create directories at import time (idempotent)
for _d in DIRS.values():
    _d.mkdir(parents=True, exist_ok=True)

# ── Waste Classifier ─────────────────────────────────────────────────────────
CLIP_MODEL_ID   = "openai/clip-vit-base-patch32"   # Hugging Face model card
WASTE_LABELS    = ["plastic waste", "organic food waste", "metal waste", "electronic waste"]
CONFIDENCE_THRESHOLD = 0.40   # below this → flagged as "uncertain"

# ── Privacy Filter ────────────────────────────────────────────────────────────
BLUR_STRENGTH   = 25          # GaussianBlur kernel size (must be odd)
CASCADE_FACE    = "haarcascade_frontalface_default.xml"
CASCADE_PLATE   = "haarcascade_russian_plate_number.xml"  # proxy for generic plates
PRIVACY_PADDING = 10          # pixels of extra padding around detected regions

# ── Accra Geographic Bounds (for validation) ─────────────────────────────────
ACCRA_LAT_RANGE = (5.45, 5.75)
ACCRA_LNG_RANGE = (-0.35, 0.05)

# ── Route Optimiser ───────────────────────────────────────────────────────────
DEPOT_LOCATION  = {"name": "Accra Central Depot", "lat": 5.5502, "lng": -0.2174}
MAX_BINS_PER_TRUCK = 20       # capacity constraint per collection truck
PRIORITY_THRESHOLD = 0.75     # fill_level above which bin is high-priority

# ── Report Generator ──────────────────────────────────────────────────────────
REPORT_LANGUAGE = "en"        # placeholder for i18n (Twi/Ga extensions)
CAMPAIGN_FOOTER = (
    "This report was generated by the IWMRO system. "
    "For queries contact Accra Metropolitan Assembly – Waste Division."
)

# ── Power BI Export ───────────────────────────────────────────────────────────
POWERBI_CSV_COLUMNS = [
    "bin_id", "location_name", "latitude", "longitude",
    "waste_type", "confidence", "fill_level",
    "collection_priority", "route_sequence",
    "truck_id", "timestamp",
]

# ── Google Sheets Integration ─────────────────────────────────────────────────
# Place your service-account JSON key at the path below (see sheets_logger.py).
# If the file is absent the sheets step is silently skipped — no error raised.
SHEETS_SPREADSHEET           = "IWMRO_Data_Log"          # pipeline write target
SHEETS_ANALYTICS_SPREADSHEET = "IWMRO_Global_Data"       # analytics read target (dashboard)
SHEETS_CREDS_FILE            = ROOT_DIR / "creds.json"   # service-account key file

# ── Scalability note (referenced in report) ──────────────────────────────────
# At 1 000+ bins the route optimiser switches from nearest-neighbour O(n²)
# to OR-Tools VRP solver (see route_optimizer.py §Scalability).
OPTIMISER_MODE  = "nearest_neighbour"   # options: "nearest_neighbour" | "ortools"

# ── Business Value Assumptions ────────────────────────────────────────────────
BASELINE_DISTANCE_FACTOR   = 1.35   # unoptimised route ≈ optimised × 1.35
FUEL_EFFICIENCY_KM_PER_L   = 8.0    # litres per km for Accra collection trucks
FUEL_PRICE_GHS_PER_L       = 14.50  # Ghana Cedis per litre of diesel (2024 est.)
AVG_SPEED_KMH              = 25.0   # average urban collection speed (km/h)
RECYCLING_RATE_PCT         = 0.22   # fraction of waste that is recyclable
AVG_BIN_WEIGHT_KG          = 12.0   # assumed average bin content weight (kg)
RECYCLING_VALUE_GHS_PER_KG = 0.80   # market value per kg of recovered recyclables

# ── Power BI ──────────────────────────────────────────────────────────────────
POWERBI_EMBED_URL = ""   # override via env var POWERBI_EMBED_URL

# ── Canva Integration ─────────────────────────────────────────────────────────
CANVA_NEXT_COLLECTION_HOURS = 48   # hours until next scheduled collection

# ── Model Evaluation — Failure Mode Cards ─────────────────────────────────────
FAILURE_MODES = [
    {
        "mode": "Low-light capture",
        "description": (
            "Night-time or poorly-lit bins reduce CLIP accuracy by an estimated 15–20%. "
            "Infrared-capable cameras are recommended for 24-hour deployments."
        ),
        "severity": "High",
    },
    {
        "mode": "Mixed waste bins",
        "description": (
            "Bins containing multiple waste categories confuse zero-shot classification. "
            "CLIP assigns the dominant visual type; minority categories are not detected."
        ),
        "severity": "Medium",
    },
    {
        "mode": "Occlusion",
        "description": (
            "Closed lids or waste bags covering bin interiors prevent visual classification. "
            "An estimated 5–8% of field bins may require physical inspection."
        ),
        "severity": "Medium",
    },
    {
        "mode": "Local waste types",
        "description": (
            "CLIP was trained on generic English-language internet imagery. Ghana-specific "
            "packaging (sachet water bags, kenkey wrappers) may be misclassified. "
            "Domain fine-tuning is recommended before production rollout."
        ),
        "severity": "Low",
    },
]

# ── Recommended RBAC Concept ──────────────────────────────────────────────────
RBAC_ROLES = [
    {
        "role":        "Admin",
        "permissions": "Full pipeline access · API key management · export all data · manage users",
    },
    {
        "role":        "Analyst",
        "permissions": "View all dashboards · download CSVs · regenerate AI reports · read-only config",
    },
    {
        "role":        "Viewer",
        "permissions": "View dashboard and zone map · download PDF reports only",
    },
]

# ── Data Governance ───────────────────────────────────────────────────────────
DATA_RETENTION_DAYS = 90   # raw images auto-purged after N days (data minimisation)
