"""
config.py — Central configuration for IWMRO.

All tuneable parameters live here so every module imports from one
place, making the system easy to adapt for production deployments
(e.g. scaling from 50 to 1 000+ bins requires only this file).
"""

from pathlib import Path

# ── Project root ────────────────────────────────────────────────────────────
ROOT_DIR = Path(__file__).parent

# ── Directory layout ─────────────────────────────────────────────────────────
DIRS = {
    "models":    ROOT_DIR / "models",
    "raw":       ROOT_DIR / "data" / "raw",
    "processed": ROOT_DIR / "data" / "processed",
    "exports":   ROOT_DIR / "data" / "exports",
}

# Create directories at import time (idempotent)
for _d in DIRS.values():
    _d.mkdir(parents=True, exist_ok=True)

# ── Waste Classifier ─────────────────────────────────────────────────────────
CLIP_MODEL_ID   = "openai/clip-vit-base-patch32"   # Hugging Face model card
WASTE_LABELS    = ["plastic waste", "organic food waste", "metal waste", "electronic waste"]
CONFIDENCE_THRESHOLD = 0.40   # below this → flagged as "uncertain"

# ── Privacy Filter ────────────────────────────────────────────────────────────
BLUR_STRENGTH   = 25          # GaussianBlur kernel size (must be odd)
CASCADE_FACE    = "haarcascade_frontalface_default.xml"
CASCADE_PLATE   = "haarcascade_russian_plate_number.xml"  # proxy for generic plates
PRIVACY_PADDING = 10          # pixels of extra padding around detected regions

# ── Accra Geographic Bounds (for validation) ─────────────────────────────────
ACCRA_LAT_RANGE = (5.45, 5.75)
ACCRA_LNG_RANGE = (-0.35, 0.05)

# ── Route Optimiser ───────────────────────────────────────────────────────────
DEPOT_LOCATION  = {"name": "Accra Central Depot", "lat": 5.5502, "lng": -0.2174}
MAX_BINS_PER_TRUCK = 20       # capacity constraint per collection truck
PRIORITY_THRESHOLD = 0.75     # fill_level above which bin is high-priority

# ── Report Generator ──────────────────────────────────────────────────────────
REPORT_LANGUAGE = "en"        # placeholder for i18n (Twi/Ga extensions)
CAMPAIGN_FOOTER = (
    "This report was generated by the IWMRO system. "
    "For queries contact Accra Metropolitan Assembly – Waste Division."
)

# ── Power BI Export ───────────────────────────────────────────────────────────
POWERBI_CSV_COLUMNS = [
    "bin_id", "location_name", "latitude", "longitude",
    "waste_type", "confidence", "fill_level",
    "collection_priority", "route_sequence",
    "truck_id", "timestamp",
]

# ── Google Sheets Integration ─────────────────────────────────────────────────
# Place your service-account JSON key at the path below (see sheets_logger.py).
# If the file is absent the sheets step is silently skipped — no error raised.
SHEETS_SPREADSHEET           = "IWMRO_Data_Log"          # pipeline write target
SHEETS_ANALYTICS_SPREADSHEET = "IWMRO_Global_Data"       # analytics read target (dashboard)
SHEETS_CREDS_FILE            = ROOT_DIR / "creds.json"   # service-account key file

# ── Scalability note (referenced in report) ──────────────────────────────────
# At 1 000+ bins the route optimiser switches from nearest-neighbour O(n²)
# to OR-Tools VRP solver (see route_optimizer.py §Scalability).
OPTIMISER_MODE  = "nearest_neighbour"   # options: "nearest_neighbour" | "ortools"
